
exclude: genas/contrib/diffusion
repos:
  # - repo: https://github.com/PyCQA/flake8.git
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/PyCQA/autoflake.git
    rev: v1.5.3
    hooks:
      - id: autoflake
        args: ["--exclude=__init__.py", "--in-place", "--recursive"]
  - repo: https://github.com/psf/black.git
    rev: 22.8.0
    hooks:
      - id: black
        args: ["--line-length=120"]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", --line-length=120]
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
